---
title: '<font size="5">`scikit-learn` Toy Datasets in Python:</font><br>Linnerrud dataset'
output:
    html_document:
        theme: paper
        highlight: textmate
        number_sections: true
        toc: true
        includes:
            before_body: ../../../google_analytics.html
---

<font size="3">

For more info, see here:  
[https://scikit-learn.org/stable/datasets/toy_dataset.html?highlight=boston#linnerrud-dataset](https://scikit-learn.org/stable/datasets/toy_dataset.html?highlight=boston#linnerrud-dataset){target="_blank"}

The **Linnerrud dataset** is loaded using `load_linnerud()`. This
returns a 'Bunch' object with the following keys:

| Key | Description |
|-----|-------------------------------------------------------------|
| `DESCR` | Description of the dataset |
| `data_filename` | Location of the CSV file containing the data being imported |
| `target_filename` | Location of the CSV file containing the target data being imported |
| `feature_names` | Names of the 3 exercises (Chins, Situps, Jumps) |
| `data` | The 20 data points for each of the 3 exercises, formatted as a 20x3 array |
| `target_names` | Names of the 3 physiological variables (Weight, Waist and Pulse) |
| `target` | The target data, namely the physiological measurements |

```{python}
from sklearn.datasets import load_linnerud

# Load the dataset
linnerud = load_linnerud()

# Show the dataset's keys
print(list(linnerud))
```

```{python}
# Description of the dataset
print(linnerud['DESCR'])
```

```{python}
# Location of the CSV file containing the data being imported
print(linnerud['data_filename'])
```

```{python}
# Location of the CSV file containing the target data being imported
print(linnerud['target_filename'])
```

```{python}
# Names of the 3 exercises (Chins, Situps, Jumps)
print(linnerud['feature_names'])
```

```{python}
# The 20 data points for each of the 3 exercises, formatted as a 20x3 array
print(linnerud['data'])
```

```{python}
# Names of the 3 physiological variables (Weight, Waist and Pulse)
print(linnerud['target_names'])
```

```{python}
# The target data, namely the physiological measurements
print(linnerud['target'])
```

The groups of data can be plotted against each other or against the target
group as follows:

```{python}
import matplotlib.pyplot as plt

# Plot
plt.scatter(linnerud['data'][:, 0], linnerud['target'][:, 0])
plt.title('Linnerrud dataset')
plt.xlabel(linnerud['feature_names'][0])
plt.ylabel(linnerud['target_names'][0])
```

The data is much easier to work with if it is converted into a data frame:

```{python}
import pandas as pd

# Extract the data
data = pd.DataFrame(linnerud['data'], columns=linnerud['feature_names'])
# Extract the target
target = pd.DataFrame(linnerud['target'], columns=linnerud['target_names'])
# Combine into one dataset
df = pd.concat([target, data], axis='columns')

# Plot
plt.scatter(df['Waist'], df['Situps'])
plt.title('Linnerrud dataset')
plt.xlabel('Waist')
plt.ylabel('Situps')
```

</font>
