---
title: '<font size="5">Utilities in Python:</font><br>Extract Text From PDFs'
output:
    html_document:
        theme: paper
        highlight: textmate
        number_sections: true
        toc: true
        includes:
            before_body: ../../google_analytics.html
---

<font size="3">

[⇦ Back](../../python.html)

Python Packages
===============
Text can be extracted from PDF documents using the **pypdf** package (read more on [PyPI](https://pypi.org/project/pypdf/), [GitHub](https://github.com/py-pdf/pypdf) and [Read the Docs](https://pypdf.readthedocs.io/en/latest/)). We will also be using the Pandas library. Install these both from the terminal with the following commands:

```bash
# "python3.12" should correspond to the version of Python you are using
python3.12 -m pip install pypdf
python3.12 -m pip install pandas
```

Once finished, you can import them into a Python script as follows:

```{python}
import pypdf
import pandas as pd
```

Example
=======
As an example of a PDF from which to extract text let's use Bland and Altman's 1986 paper "Statistical methods for assessing agreement between two methods of clinical measurement"[^1]. This is the [29th most-cited paper](https://www.nature.com/news/the-top-100-papers-1.16224) of all time, so it's quite a popular one! It can be downloaded from [here](https://www-users.york.ac.uk/~mb55/meas/ba.pdf), which is a part of Bland's [own site](https://www-users.york.ac.uk/~mb55/index.html).

[^1]: Bland JM, Altman DG. Statistical methods for assessing agreement between two methods of clinical measurement. *Lancet*. 1986;327(8476): 307–310. DOI: [10.1016/s0140-6736(86)90837-8](https://doi.org/10.1016/s0140-6736(86)90837-8). PMID: [2868172](https://pubmed.ncbi.nlm.nih.gov/2868172). Available [here](https://www-users.york.ac.uk/~mb55/meas/ba.pdf). Jump to reference:&nbsp;

Once you've downloaded the PDF, move it into the same folder as your Python script and you'll be able to use pypdf from there:

```{python}
# Download this PDF from https://www-users.york.ac.uk/~mb55/meas/ba.pdf
pdf = pypdf.PdfReader('ba.pdf')
```

Once imported into Python, the number of pages in the PDF can be accessed as an attribute:

```{python}
number_of_pages = len(pdf.pages)
print(f'Number of pages in this PDF: {number_of_pages}')
```

Get the first of these pages, extract the text and split it into individual lines:

```{python}
page = pdf.pages[0]
text = page.extract_text()
lines = text.split('\n')
for line in lines[:3]:
    print(line)
```

You'll notice that the page number appears at the start of the first line. This is annoying, but it's a manageable glitch.

Next, let's access the raw data on page 2:

```{python}
page = pdf.pages[1]
text = page.extract_text()
lines = text.split('\n')
for line in lines[1:21]:
    print(line)
```

This is great! We can import the data into Python directly from the PDF! Of course, it will be more usable in a data frame format so let's use Pandas and re-structure it:

```{python}
# Initialise the output data frame
df = pd.DataFrame()
# Iterate over the lines extracted from the PDF
for line in lines[4:21]:
    # Remove duplicate white space
    line = ' '.join(line.split())
    # Split into its elements
    line = line.split()
    # Construct a new row with a MultiIndex as the column names
    data = [[line[1], line[2], line[3], line[4]]]
    arrays = [
        ['Wright'] * 2 + ['Mini Wright'] * 2,
        ['First', 'Second'] * 2,
    ]
    tuples = list(zip(*arrays))
    columns = pd.MultiIndex.from_tuples(tuples)
    new_row = pd.DataFrame(data, index=[line[0]], columns=columns)
    # Add to master data frame
    df = pd.concat([df, new_row])
print(df)
```

See [here](../statistics/agreement/bland_altman.html) for how to continue the analysis of Bland and Altman's data.

[⇦ Back](../../python.html)

</font>
