---
title: '<font size="5">Introduction to R:</font><br>Maths and Numbers'
output:
    html_document:
        theme: paper
        highlight: textmate
        # number_sections: true
        # toc: true
        includes:
            before_body: ../../google_analytics.html
---

<font size="3">

[⇦ Back](../../R.html)

# Arithmetic
All the usual mathematical operations can be done in R:

```{r}
# Addition and subtraction
a <- 4 + 5 - 2
# Multiplication and division
b <- 2 * 100 / 4
# Integer division
c <- 47 %/% 5
# Exponent
d <- 2 ^ 4
# Modulus
e <- 5 %% 13

# Output to console
c(a, b, c, d, e)
```

For more complicated operations there are functions to do it for you:

```{r}
# Square root
a <- sqrt(49)
# Round down
b <- floor(-6.28318531)
# Round up
c <- ceiling(-6.28318531)
# Round towards zero
d <- trunc(-6.28318531)
# Round to a certain number of decimal places
e <- round(-6.28318531, 3)
# Round to a certain number of significant figures
f <- signif(-6.28318531, 3)

# Output to console
c(a, b, c, d, e, f)

# Remove trailing zeros
# Note that this converts the number to a string
g <- prettyNum(-6.28000, zero.print = NULL)
g
```

[⇦ Back](../../R.html)

</font>
