# NEEDED BY DEBIAN
# sudo apt-get install libssl-dev
# sudo apt-get install libcurl4-openssl-dev

# install.packages("BlandAltmanLeh", repos = "http://cran.us.r-project.org")
# install.packages("brglm2", repos = "http://cran.us.r-project.org")
# install.packages("chron", repos = "http://cran.us.r-project.org")
# install.packages("DiagrammeR", repos = "http://cran.us.r-project.org")
# install.packages("dplyr", repos = "https://cloud.r-project.org/bin/linux/ubuntu")
# install.packages("emmeans", repos = "http://cran.us.r-project.org")
# install.packages("forestplot", repos = "http://cran.us.r-project.org")
# install.packages("ggplot2", repos = "http://cran.us.r-project.org")
# install.packages("ggpubr", repos = "http://cran.us.r-project.org")
# install.packages("kableExtra", repos = "http://cran.us.r-project.org")
# install.packages("knitr", repos = "http://cran.us.r-project.org")
# install.packages("lintr", repos = "http://cran.us.r-project.org")
# install.packages("logging", repos = "http://cran.us.r-project.org")
# install.packages("maps", repos = "http://cran.us.r-project.org")
# install.packages("matrixStats", repos = "http://cran.us.r-project.org")
# install.packages("mcr", repos = "http://cran.us.r-project.org")
# install.packages("pROC", repos = "http://cran.us.r-project.org")
# install.packages("Rmisc", repos = "http://cran.us.r-project.org")
# install.packages("R.utils", repos = "http://cran.us.r-project.org")
# install.packages("readr", repos = "http://cran.us.r-project.org")
# install.packages("reticulate", repos = "http://cran.us.r-project.org")
# install.packages("rmarkdown", repos = "http://cran.us.r-project.org")
# install.packages("stringi", repos = "http://cran.us.r-project.org")
# install.packages("stringr", repos = "http://cran.us.r-project.org")
# install.packages("titanic", repos = "http://cran.us.r-project.org")
# install.packages("utf8", repos = "http://cran.us.r-project.org")

library(BlandAltmanLeh)
library(brglm2)
library(chron)
library(DiagrammeR)
library(dplyr)
library(emmeans)
library(forestplot)
library(ggplot2)
library(ggpubr)
library(kableExtra)
library(knitr)
library(lintr)
library(logging)
library(maps)
# library(matrixStats)  # Couldn't install with R 4.x.x
library(mcr)
library(pROC)
library(Rmisc)
library(R.utils)
library(readr)
library(reticulate)
library(rmarkdown)
library(stringi)
library(stringr)
library(titanic)
library(utf8)
