# Needed by Debian:
# sudo apt-get install libssl-dev
# sudo apt-get install libcurl4-openssl-dev
# REPO FOR UBUNTU
# https://cloud.r-project.org/bin/linux/ubuntu

install.packages("BlandAltmanLeh", repos = "http://cran.us.r-project.org")
install.packages("brglm2", repos = "http://cran.us.r-project.org")
install.packages("chron", repos = "http://cran.us.r-project.org")
install.packages("devtools", repos = "http://cran.us.r-project.org")
install.packages("DiagrammeR", repos = "http://cran.us.r-project.org")
install.packages("dplyr", repos = "http://cran.us.r-project.org")
install.packages("emmeans", repos = "http://cran.us.r-project.org")
install.packages("forestplot", repos = "http://cran.us.r-project.org")
install.packages("formatR", repos = "http://cran.us.r-project.org")
install.packages("gapminder", repos = "http://cran.us.r-project.org")
install.packages("ggplot2", repos = "http://cran.us.r-project.org")
install.packages("ggpubr", repos = "http://cran.us.r-project.org")
install.packages("gtools", repos = "http://cran.us.r-project.org")
install.packages("Hmisc", repos = "http://cran.us.r-project.org")  # Could not install on Ubunut 18.04 with R 4.0.2
install.packages("ini", repos = "http://cran.us.r-project.org")
install.packages("kableExtra", repos = "http://cran.us.r-project.org")
install.packages("knitr", repos = "http://cran.us.r-project.org")
install.packages("lintr", repos = "http://cran.us.r-project.org")
install.packages("logging", repos = "http://cran.us.r-project.org")
install.packages("maps", repos = "http://cran.us.r-project.org")
install.packages("mcr", repos = "http://cran.us.r-project.org")
install.packages("pdftools", repos = "http://cran.us.r-project.org")
install.packages("pROC", repos = "http://cran.us.r-project.org")
install.packages("psych", repos = "http://cran.us.r-project.org")
install.packages("readtext", repos = "http://cran.us.r-project.org")
install.packages("reshape2", repos = "http://cran.us.r-project.org")  # Could not install on Ubunut 18.04 with R 4.0.2
install.packages("Rmisc", repos = "http://cran.us.r-project.org")
install.packages("R.utils", repos = "http://cran.us.r-project.org")
install.packages("readr", repos = "http://cran.us.r-project.org")
install.packages("reticulate", repos = "http://cran.us.r-project.org")
install.packages("rmarkdown", repos = "http://cran.us.r-project.org")
install.packages("stringi", repos = "http://cran.us.r-project.org")
install.packages("stringr", repos = "http://cran.us.r-project.org")
install.packages("styler", repos = "http://cran.us.r-project.org")
install.packages("tidyverse", repos = "http://cran.us.r-project.org")
install.packages("titanic", repos = "http://cran.us.r-project.org")
install.packages("utf8", repos = "http://cran.us.r-project.org")
install.packages("xtable", repos = "http://cran.us.r-project.org")

library(BlandAltmanLeh)
library(brglm2)
library(chron)
library(devtools)
library(DiagrammeR)
library(dplyr)
library(emmeans)
library(forestplot)
library(formatR)
library(gapminder)
library(ggplot2)
library(ggpubr)
library(gtools)
library(Hmisc)
library(ini)
library(kableExtra)
library(knitr)
library(lintr)
library(logging)
library(maps)
library(mcr)
library(pdftools)
library(pROC)
library(psych)
library(readtext)
library(reshape2)
library(Rmisc)
library(R.utils)
library(readr)
library(reticulate)
library(rmarkdown)
library(stringi)
library(stringr)
library(styler)
library(tidyverse)
library(titanic)
library(utf8)
library(xtable)

# Couldn't install with R 4.x.x
# install.packages("matrixStats", repos = "http://cran.us.r-project.org")
# library(matrixStats)

# Full run
# [Finished in 384.6s]
