# install.packages("BlandAltmanLeh", repos = "http://cran.us.r-project.org")
# install.packages("brglm2", repos = "http://cran.us.r-project.org")
# install.packages("Cairo", repos = "http://cran.us.r-project.org")
# install.packages("chron", repos = "http://cran.us.r-project.org")
# install.packages("clinspacy", repos = "http://cran.us.r-project.org")
# install.packages("devtools", repos = "http://cran.us.r-project.org")
# install.packages("DiagrammeR", repos = "http://cran.us.r-project.org")
# install.packages("dplyr", repos = "http://cran.us.r-project.org")
# install.packages("emmeans", repos = "http://cran.us.r-project.org")
# install.packages("epiR", repos = "http://cran.us.r-project.org")
# install.packages("exact2x2", repos = "http://cran.us.r-project.org")
# install.packages("extrafont", repos = "http://cran.us.r-project.org")
# install.packages("flextable", repos = "http://cran.us.r-project.org")
# install.packages("forestplot", repos = "http://cran.us.r-project.org")
# install.packages("formatR", repos = "http://cran.us.r-project.org")
# install.packages("gapminder", repos = "http://cran.us.r-project.org")
# install.packages("ggplot2", repos = "http://cran.us.r-project.org")
# install.packages("ggpubr", repos = "http://cran.us.r-project.org")
# install.packages("grDevices", repos = "http://cran.us.r-project.org")
# install.packages("gtools", repos = "http://cran.us.r-project.org")
# install.packages("Hmisc", repos = "http://cran.us.r-project.org")
# install.packages("ini", repos = "http://cran.us.r-project.org")
# install.packages("kableExtra", repos = "http://cran.us.r-project.org")
# install.packages("knitr", repos = "http://cran.us.r-project.org")
# install.packages("knotR", repos = "http://cran.us.r-project.org")
# install.packages("lintr", repos = "http://cran.us.r-project.org")
# install.packages("logging", repos = "http://cran.us.r-project.org")
# install.packages("magick", repos = "http://cran.us.r-project.org")
# install.packages("maps", repos = "http://cran.us.r-project.org")
# install.packages("matrixStats", repos = "http://cran.us.r-project.org")
# install.packages("mcr", repos = "http://cran.us.r-project.org")
# install.packages("officer", repos = "http://cran.us.r-project.org")
# install.packages("openxlsx", repos = "http://cran.us.r-project.org")
# install.packages("pdftools", repos = "http://cran.us.r-project.org")
# install.packages("pROC", repos = "http://cran.us.r-project.org")
# install.packages("psych", repos = "http://cran.us.r-project.org")
# install.packages("readtext", repos = "http://cran.us.r-project.org")
# install.packages("reshape", repos = "http://cran.us.r-project.org")
# install.packages("reshape2", repos = "http://cran.us.r-project.org")
# install.packages("Rmisc", repos = "http://cran.us.r-project.org")
# install.packages("R.utils", repos = "http://cran.us.r-project.org")
# install.packages("readr", repos = "http://cran.us.r-project.org")
# install.packages("reticulate", repos = "http://cran.us.r-project.org")
# install.packages("rmarkdown", repos = "http://cran.us.r-project.org")
# install.packages("stringi", repos = "http://cran.us.r-project.org")
# install.packages("stringr", repos = "http://cran.us.r-project.org")
# install.packages("styler", repos = "http://cran.us.r-project.org")
# install.packages("survminer", repos = "http://cran.us.r-project.org")
# install.packages("tidyverse", repos = "http://cran.us.r-project.org")
# install.packages("titanic", repos = "http://cran.us.r-project.org")
# install.packages("utf8", repos = "http://cran.us.r-project.org")
# install.packages("writexl", repos = "http://cran.us.r-project.org")
# install.packages("WriteXLS", repos = "http://cran.us.r-project.org")
# install.packages("xlsx", repos = "http://cran.us.r-project.org")
# install.packages("Xmisc", repos = "http://cran.us.r-project.org")
# install.packages("xtable", repos = "http://cran.us.r-project.org")

library(BlandAltmanLeh)
library(brglm2)
library(Cairo)
library(chron)
library(clinspacy)
library(devtools)
library(DiagrammeR)
library(dplyr)
library(emmeans)
library(epiR)
library(exact2x2)
library(extrafont)
library(flextable)
library(forestplot)
library(formatR)
library(gapminder)
library(ggplot2)
library(ggpubr)
library(grDevices)
library(gtools)
library(Hmisc)
library(ini)
library(kableExtra)
library(knitr)
library(knotR)
library(lintr)
library(logging)
library(magick)
library(maps)
library(matrixStats)
library(mcr)
library(officer)
library(openxlsx)
library(pdftools)
library(pROC)
library(psych)
library(readtext)
library(reshape)
library(reshape2)
library(Rmisc)
library(R.utils)
library(readr)
library(reticulate)
library(rmarkdown)
library(stringi)
library(stringr)
library(styler)
library(survminer)
library(tidyverse)
library(titanic)
library(utf8)
library(writexl)
library(WriteXLS)
library(xlsx)
library(Xmisc)
library(xtable)

# Full run
# [Finished in 384.6s]

# Troubleshooting
# ---------------
#
# ### clinspacy
# - https://github.com/ML4LHS/clinspacy
# - For clinspacy to work you need Python installed:
#     - Download Python from https://www.python.org/
#     - A shortcut to downloading Python 3.8 is here:
#       https://www.python.org/ftp/python/3.8.10/python-3.8.10-macosx10.9.pkg
# - Run the following in R (you might need to change the `use_python()` path
#   if you have a version of Python that isn't 3.8 installed and/or you have
#   it installed to a different location):
# library(clinspacy)
# clinspacy_init(miniconda = FALSE)
# library(reticulate)
# path = "/Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8"
# reticulate::use_python(path)
# clinspacy("This patient has diabetes and CKD stage 3 but no HTN.")
