# NEEDED BY DEBIAN
# sudo apt-get install libssl-dev
# sudo apt-get install libcurl4-openssl-dev

# install.packages("BlandAltmanLeh", repos = "http://cran.us.r-project.org")
# install.packages("chron", repos = "http://cran.us.r-project.org")
# install.packages("DiagrammeR", repos = "http://cran.us.r-project.org")
# install.packages("dplyr", repos = "https://cloud.r-project.org/bin/linux/ubuntu")
# install.packages("ggplot2", repos = "http://cran.us.r-project.org")
# install.packages("lintr", repos = "http://cran.us.r-project.org")
# install.packages("logging", repos = "http://cran.us.r-project.org")
# install.packages("matrixStats", repos = "http://cran.us.r-project.org")
# install.packages("Rmisc", repos = "http://cran.us.r-project.org")
# install.packages("R.utils", repos = "http://cran.us.r-project.org")
# install.packages("readr", repos = "http://cran.us.r-project.org")
# install.packages("reticulate", repos = "http://cran.us.r-project.org")
# install.packages("rmarkdown", repos = "http://cran.us.r-project.org")
# install.packages("stringi", repos = "http://cran.us.r-project.org")
# install.packages("stringr", repos = "http://cran.us.r-project.org")
# install.packages("utf8", repos = "http://cran.us.r-project.org")

library(BlandAltmanLeh)
library(chron)
library(DiagrammeR)
library(dplyr)
library(ggplot2)
library(lintr)
library(logging)
library(matrixStats)
library(Rmisc)
library(R.utils)
library(readr)
library(reticulate)
library(rmarkdown)
library(stringi)
library(stringr)
library(utf8)
