---
title: '<font size="5">Graphs in Python:</font><br>Control the Image Size of Your Plots'
output:
    html_document:
        theme: paper
        highlight: textmate
---
<font size="3">

[⇦ Back](../../python.html)

Once you start plotting graphs that you want to do something with (eg adding them to a report, or a thesis, or a poster) you'll probably want to start changing their size, shape and quality (among other things). One option would be to take control of the exact dimensions of the graphs - in pixels or length or whatever - but this can get confusing pretty quickly. It can also make it difficult to have all your graphs' formats consistent or to quickly make changes to them all. One solution is to standardise them using the [A series of international paper sizes](https://en.wikipedia.org/wiki/Paper_size#A_series): A0, A1, A2, etc.

A Series
--------
There are three rules that determine the dimensions of A0, A1, A2, etc, pages:

- If $a$ is the length of the long side of the page and $b$ the length of the short side then $\frac{a}{b} = \sqrt{2} = 1.412..$
- The A0 size has an area of exactly 1 m<sup>2</sup>
- Each successive page size (A1, A2, etc) has half the area of the previous

Together, these three rules mean that a page of size A$x$ has an area $A$ of $0.5^x$ m<sup>2</sup> and:

$a = \sqrt{2}b$

$b = \frac{a}{\sqrt{2}}$

Therefore, as $A = a \times b = 0.5^x$:

$\frac{a^2}{\sqrt{2}} = 0.5^x$

$\rightarrow a = \sqrt{\sqrt{2} \times 0.5^x}$

$\rightarrow a = 1.189 \times 0.5^{0.5x}$

and:

$\sqrt{2} b^2 = 0.5^x$

$\rightarrow b = \sqrt{\frac{1}{\sqrt{2}} \times 0.5^x}$

$\rightarrow b = 0.841 \times 0.5^{0.5x}$

These dimensions can be fed into Python to set the size of your plots but, unfortunately, this needs to be done in inches. So we need to convert from metres by multiplying by 39.37:

$a = 46.82 \times 0.5^{0.5x}$ in

$b = 33.11 \times 0.5^{0.5x}$ in

The Python code then looks like this:

```{python}
import matplotlib.pyplot as plt

x = 6  # WE WANT FIGURES TO BE A6
plt.rc('figure', figsize=[46.82 * .5**(.5 * x), 33.11 * .5**(.5 * x)])

x = [0, 1, 2, 3, 4, 5, 6]
y = [0, 1, 4, 9, 16, 25, 36]
plt.plot(x, y)
plt.title('This Image is A6')
plt.show()
```

[⇦ Back](../../python.html)

</font>
