---
title: '<font size="5">Graphs in Python:</font><br>Use Latex in Plot Labels'
output:
    html_document:
        theme: paper
        highlight: textmate
        includes:
            before_body: ../../google_analytics.html
---

<font size="3">

[⇦ Back](../../python.html)

In order to access the power of Latex when creating text as part of a graph you need to change some of the 'rc parameters'. These are the default settings for your plots: 'rc' stands for 'run commands' which tells you that these are the commands are executed at runtime (ie the moment when you run Python, even before your code gets executed). The two most important rc parameters to change are:

- `text.usetex` which needs to be set to `True`
- `font.family` which needs to be changed to `serif` to use Latex's classic Computer Modern font

Also, we need to append the letter `r` to the strings that contain Latex. This lets Python know to treat the Latex commands as functions, not as literal text.

Here's what it looks like:

```{python}
import matplotlib.pyplot as plt
import numpy as np

# Settings
x = 6  # Want figures to be A6
plt.rc('figure', figsize=[46.82 * .5**(.5 * x), 33.11 * .5**(.5 * x)])
plt.rc('text', usetex=True)
plt.rc('font', family='serif')

# Create some data
x = np.arange(100)
y = x**2

# Plot
plt.plot(x, y)
plt.title(r'\LaTeX\ in Labels')
plt.xlabel(r'Time, $t$ [\textmu s]')
plt.text(70, 7000, r'$R = t^2$')
```

Notice that we can use both Latex's math mode for equations (eg "$R = t^2$"") and text mode for upright text (eg "&mu;s" in the x-axis label). To use upright Greek letters in text mode, as has been done here, the only letter that will work out-of-the-box is mu (&mu;). This is because the command that does this (`\textmu`) is included in the `textcomp` package which is loaded by default. To use other upright Greek letter in text mode we need to use the `textgreek` package which can be loaded in the Latex preamble by changing another rc parameter:

- `text.latex.preamble` sets what commands are run in Latex's preamble

This gives us access to, for example, `\textOmega`. Have a look:

```{python}
plt.rc('text.latex', preamble=r'\usepackage{textgreek}')

# Plot
plt.plot(x, y)
plt.title(r'\LaTeX\ in Labels')
plt.xlabel(r'Time, $t$ [\textmu s]')
plt.ylabel(r'Resistance, $R$ [\textOmega]')
plt.text(70, 7000, r'$R = t^2$')
```

Finally, note that we can combine "r-strings" with "f-strings" to create "fr-strings", accessing both the typesetting power of Latex AND the string formatting power of Python:

```{python}
plt.plot(x, y)
plt.title(r'\LaTeX\ in Labels')
# \textmu works out-of-the-box
plt.xlabel(r'Time, $T$ [\textmu s]')
# Other Greek letters need the textgreek package
plt.ylabel(r'Resistance, $R$ [\textOmega]')
# Add annotations
mean_y = np.mean(y)
ylim = plt.ylim(min(y), max(y))
xlim = plt.xlim(min(x), max(x))
plt.vlines(np.sqrt(mean_y), ymin=0, ymax=mean_y, linestyles='dashed')
plt.hlines(mean_y, xmin=0, xmax=np.sqrt(mean_y), linestyles='dashed')
plt.text(10, mean_y + 150, fr'Mean resistance, \textsigma\ = {np.mean(y)}\textOmega')
plt.text(70, 7000, r'$R = t^2$')
```

Troubleshooting
===============

Style Files
-----------
If you get an error such as:
```
! LaTeX Error: File `textgreek.sty' not found.
```
It means that you are missing the Latex style file that was mentioned in the error and should manually install it:

- Go to [CTAN](https://www.ctan.org/), search for and download the required package (in this example it's "textgreek")
- It will either download as a `.sty` file or as a `.zip` file. If the latter, unzip it and run Latex on the `.ins` and `.dtx` files (eg by opening the folder in a terminal and running `latex textgreek.ins`) which will create the `.sty` file.
    - Follow any advice printed to the terminal, eg with how to run the `.dtx` file
- Move the `.sty` file to an appropriate directory, eg `/usr/share/texmf/tex/latex` on Ubuntu
- Update the ls-R file in this source tree. Because the folder you moved the `.sty` file into might not be searched by default, the ls-R file must be updated to make the system aware of the new package.

On Ubuntu, the last two points can be done from the terminal with:

```{bash, eval=FALSE}
sudo mv <package>.sty /usr/share/texmf/tex/latex/<package>.sty
sudo mktexlsr
```

Language Elements
-----------------
If you get something like:

```
! Package textgreek Error: Cannot find the file lgrenc.def.
```

This is a Debian error with the textgreek package. Fix it with:

```{bash, eval=FALSE}
sudo apt install texlive-lang-greek
```

[⇦ Back](../../python.html)

</font>
