---
title: '<font size="5">Graphs in R using plot():</font><br>Symbol Types in Scatter Plots'
output:
    html_document:
        theme: paper
        highlight: textmate
        number_sections: true
        toc: true
        includes:
            before_body: ../../../google_analytics.html
---

<font size="3">
    
[⇦ Back](../../../R.html)

By default, there are 26 symbols that can be used for the points of a scatter plot. These are numbered from 0 to 25 as follows:

<style>
  .col2 {
    columns: 2 200px;         /* number of columns and width in pixels*/
    -webkit-columns: 2 200px; /* chrome, safari */
    -moz-columns: 2 200px;    /* firefox */
  }
  .col3 {
    columns: 3 100px;
    -webkit-columns: 3 100px;
    -moz-columns: 3 100px;
  }
</style>

<div class="col2">

| pch = | Symbol |
|-------|--------|
| 0     | square |
| 1     | circle |
| 2     | triangle point up |
| 3     | plus |
| 4     | cross |
| 5     | diamond |
| 6     | triangle point down |
| 7     | square cross |
| 8     | star |
| 9     | diamond plus |
| 10    | circle plus |
| 11    | triangles up and down |
| 12    | square plus |

| pch = | Symbol |
|-------|--------|
| 13    | circle cross |
| 14    | square and triangle down |
| 15    | filled square |
| 16    | filled circle |
| 17    | filled triangle point-up |
| 18    | filled diamond |
| 19    | solid circle |
| 20    | bullet (smaller circle) |
| 21    | filled circle blue |
| 22    | filled square blue |
| 23    | filled diamond blue |
| 24    | filled triangle point-up blue |
| 25    | filled triangle point down blue |

</div>

This is what they look like:

```{r, echo=FALSE, results='hold', out.width='100%'}
number2type = data.frame(
	number=c(0:25),
	name=c(
        'square', 'circle', 'triangle point up', 'plus', 'cross', 'diamond',
        'triangle point down', 'square cross', 'star', 'diamond plus',
        'circle plus', 'triangles up and down', 'square plus', 'circle cross',
        'square and triangle down', 'filled square', 'filled circle',
        'filled triangle point-up', 'filled diamond', 'solid circle',
        'bullet (smaller circle)', 'filled circle blue', 'filled square blue',
        'filled diamond blue', 'filled triangle point-up',
        'filled triangle point dwn'
    )
)
x = anscombe$x1
y = anscombe$y1
par(mfrow=c(2, 3))
for (i in 0:25) {
	plot(x, y, pch=i, ylab='', xlab='', main=sprintf('pch = %i: %s', i, number2type$name[i + 1]))
}
```

[⇦ Back](../../../R.html)

</font>
