---
title: '<font size="5">Graphs in Python:</font><br>Receiver Operating Characteristic Curves'
output:
    html_document:
        theme: paper
        highlight: textmate
        number_sections: true
        toc: true
---
<font size="3">

[⇦ Back](../../../python.html)

*This page only focuses on **plotting** ROC curves, not on how to do a full diagnostic accuracy analysis.*

Data
====
For this page we will use the Titanic dataset; a database of the passengers aboard the ill-fated Titanic passenger ship that sunk in 1912. Specifically, we will be asking the question:

> Can the amount of money a passenger paid for their ticket be used to predict whether or not they survived?

As such, the **fare** that they paid will be used as the *score* data and whether or not they **survived** (where `1 = survived` and `0 = died`) will be used as the *true* data.

The data can be downloaded from the Stanford website using Pandas:

```{python, results='hide'}
import pandas as pd

# SETTINGS FOR DISPLAYING PANDAS DATA FRAMES
pd.set_option('display.max_columns', 20)
pd.set_option('display.max_colwidth', 20)
pd.set_option('display.width', 1000)

# DOWNLOAD DATA
df = pd.read_csv('https://web.stanford.edu/class/archive/cs/cs109/cs109.1166/stuff/titanic.csv')
# SHOW DATA
print(df.head().to_html(index=False))
```

The first five rows look like this:

<div id="striped" class="section level1">
<table class="table table-striped" style="margin-left: auto; margin-right: auto;">
<thead>

<tr style="text-align: right;">
  <th>Survived</th>
  <th>Pclass</th>
  <th>Name</th>
  <th>Sex</th>
  <th>Age</th>
  <th>Sib/Spou</th>
  <th>Par/Child</th>
  <th>Fare</th>
</tr>
<tr>
  <td>0</td>
  <td>3</td>
  <td>Mr. Owen Harris Braund</td>
  <td>male</td>
  <td>22.0</td>
  <td>1</td>
  <td>0</td>
  <td>7.2500</td>
</tr>
<tr>
  <td>1</td>
  <td>1</td>
  <td>Mrs. John Bradley (Florence Briggs Thayer) Cumings</td>
  <td>female</td>
  <td>38.0</td>
  <td>1</td>
  <td>0</td>
  <td>71.2833</td>
</tr>
<tr>
  <td>1</td>
  <td>3</td>
  <td>Miss. Laina Heikkinen</td>
  <td>female</td>
  <td>26.0</td>
  <td>0</td>
  <td>0</td>
  <td>7.9250</td>
</tr>
<tr>
  <td>1</td>
  <td>1</td>
  <td>Mrs. Jacques Heath (Lily May Peel) Futrelle</td>
  <td>female</td>
  <td>35.0</td>
  <td>1</td>
  <td>0</td>
  <td>53.1000</td>
</tr>
<tr>
  <td>0</td>
  <td>3</td>
  <td>Mr. William Henry Allen</td>
  <td>male</td>
  <td>35.0</td>
  <td>0</td>
  <td>0</td>
  <td>8.0500</td>
</tr>
</tbody>
</table>
</div>

Create ROC Curve from First Principles
======================================
First, import the necessary libraries and customise the settings you will use for all your plots:

```{python}
import matplotlib.pyplot as plt
import numpy as np

# WANT FIGURES TO BE A6
x = 6
plt.rc('figure', figsize=[46.82 * .5**(.5 * x), 33.11 * .5**(.5 * x)])
# USE LATEX FOR THE PLOT LABELS
plt.rc('text', usetex=True)
# USE A SERIF FONT FOR THE PLOT LABELS
plt.rc('font', family='serif')
# BE ABLE TO USE GREEK SYMBOLS IN THE PLOT LABELS
plt.rc('text.latex', preamble=r'\usepackage{textgreek}')
```

Next, extract the data you will be using to create the ROC curve from the data frame. In our case, the "Fare" is the score data and "Survived" is the truth/outcome data:

```{python}
# EXTRACT THE DATA OF INTEREST FROM THE DATA FRAME
y = df['Survived'].values
score = df['Fare'].values
```

Next, initialise the variables that will be used for generating the plot:

- The true positive rates (sensitivity) will be plotted on the y-axis, the false positive rates (1-specificity) will be plotted on the x-axis
- The thresholds will be each of the cut-off values (for, in this case, ticket fare) for which a true and false positive rate will be calculated. We can thus just use the fare prices themselves, plus 0, which guarantees that there will be no-one who paid less than the minimum threshold (as no-one paid less than 0) or more than the maximum threshold (as no-one paid more than the highest fare).
- The total number of positive outcomes (people who survived) and negative outcomes (people who died) is needed for calculating rate

```{python}
# INITIALISE THE FALSE POSITIVE RATES
fpr = []
# INITIALISE THE TRUE POSITIVE RATES
tpr = []
# THRESHOLDS TO ITERATE THROUGH
thresholds = [0] + sorted(score)
# GET THE NUMBER OF POSITIVE AND NEGATIVE RESULTS
P = sum(y)
N = len(y) - P
```

For each threshold (ie for each fare price), calculate the true and false positive rate associated with using it as a cut-off for predicting survival:

```{python}
# ITERATE THROUGH ALL THRESHOLDS AND DETERMINE THE FRACTION OF TRUE POSITIVES
# AND FALSE NEGATIVES FOUND AT EVERY THRESHOLD
for threshold in thresholds:
    FP = 0
    TP = 0
    for i in range(len(score)):
        if (score[i] > threshold):
            if y[i] == 1:
                TP += 1
            if y[i] == 0:
                FP += 1
    fpr.append(FP / float(N))
    tpr.append(TP / float(P))
```

Convert the false positive rate to specificity (which is what is more usually plotted):

```{python}
# GET SPECIFICITY FROM FALSE POSITIVE RATE
spec = [1 - x for x in fpr]
```

Use the trapezoidal rule to calculate the area under the curve:

```{python}
# GET THE AREA UNDER THE CURVE FROM THE TRAPEZOIDAL RULE (USING NUMPY)
AUC = -np.trapz(spec, tpr)
```

Now we can use Matplotlib to create the plot:

```{python, results='hide', eval=FALSE}
#
# PLOT
#
ax = plt.axes()
# USE AN F-STRING TO INCLUDE THE AUC IN THE TITLE
ax.set_title(
    'Receiver Operating Characteristic Curve\n'
    f'(AUC = {AUC:4.2})'
)
# PLOT THE ROC CURVE
ax.plot(spec, tpr, 'k-')
# PLOT THE DIAGONAL LINE (BE CAREFUL TO NOT START AT THE ORIGIN)
ax.plot([1, 0], [0, 1], 'k-', alpha=0.3)
# REVERSE THE X-AXIS
ax.set_xlim([1, 0])
ax.set_ylim([0, 1])
ax.set_xlabel('Specificity')
ax.set_ylabel('Sensitivity')
# MAKE THE PLOT SQUARE
ax.set_aspect(abs(max(fpr) - min(fpr)) / abs(max(tpr) - min(tpr)))
plt.show()
plt.close()
```

```{python, results='hide', echo=FALSE}
#
# PLOT
#
ax = plt.axes()
# USE AN F-STRING TO INCLUDE THE AUC IN THE TITLE
ax.set_title(
    'Receiver Operating Characteristic Curve\n'
    f'(AUC = {AUC:4.2})'
)
# PLOT THE ROC CURVE
ax.plot(spec, tpr, 'k-')
# PLOT THE DIAGONAL LINE (BE CAREFUL TO NOT START AT THE ORIGIN)
ax.plot([1, 0], [0, 1], 'k-', alpha=0.3)
# REVERSE THE X-AXIS
ax.set_xlim([1, 0])
ax.set_ylim([0, 1])
ax.set_xlabel('Specificity')
ax.set_ylabel('Sensitivity')
# MAKE THE PLOT SQUARE
ax.set_aspect(abs(max(fpr) - min(fpr)) / abs(max(tpr) - min(tpr)))
plt.show()
plt.close()
```

Create ROC Curve Using scikit-learn
===================================
Now repeat the process using the functions provided by the `sklearn` package. This is not only quicker in terms of number of lines of code but it also runs quicker:

```{python, results='hide', eval=FALSE}
import pandas as pd
import matplotlib.pyplot as plt
import sklearn.metrics as metrics

# DOWNLOAD DATA
df = pd.read_csv('https://web.stanford.edu/class/archive/cs/cs109/cs109.1166/stuff/titanic.csv')

# EXTRACT THE DATA OF INTEREST FROM THE DATA FRAME
y = df['Survived'].values
score = df['Fare'].values
# GENERATE THE FALSE POSITIVE RATES, TRUE POSITIVE RATES AND THRESHOLDS
fpr, tpr, thresholds = metrics.roc_curve(y, score)
# GENERATE THE AREA UNDER THE CURVE
# EQUIVALENT TO auc = metrics.roc_auc_score(y, score)
auc = metrics.auc(fpr, tpr)
# GET SPECIFICITY FROM FALSE POSITIVE RATE
spec = [1 - x for x in fpr]

#
# PLOT
#
ax = plt.axes()
# USE AN F-STRING TO INCLUDE THE AUC IN THE TITLE
ax.set_title(
    'Receiver Operating Characteristic\n' +
    f'(AUC = {auc:4.2f})'
)
# PLOT THE ROC CURVE
ax.plot(spec, tpr, 'k-')
# PLOT THE DIAGONAL LINE (BE CAREFUL TO NOT START AT THE ORIGIN)
ax.plot([1, 0], [0, 1], 'k-', alpha=0.3)
# REVERSE THE X-AXIS
ax.set_xlim([1, 0])
ax.set_ylim([0, 1])
ax.set_xlabel('Specificity')
ax.set_ylabel('Sensitivity')
# MAKE THE PLOT SQUARE
ax.set_aspect(abs(max(fpr) - min(fpr)) / abs(max(tpr) - min(tpr)))
plt.show()
plt.close()
```

```{python, results='hide', echo=FALSE}
import pandas as pd
import matplotlib.pyplot as plt
import sklearn.metrics as metrics

# DOWNLOAD DATA
df = pd.read_csv('https://web.stanford.edu/class/archive/cs/cs109/cs109.1166/stuff/titanic.csv')

# EXTRACT THE DATA OF INTEREST FROM THE DATA FRAME
y = df['Survived'].values
score = df['Fare'].values
# GENERATE THE FALSE POSITIVE RATES, TRUE POSITIVE RATES AND THRESHOLDS
fpr, tpr, thresholds = metrics.roc_curve(y, score)
# GENERATE THE AREA UNDER THE CURVE
# EQUIVALENT TO auc = metrics.roc_auc_score(y, score)
auc = metrics.auc(fpr, tpr)
# GET SPECIFICITY FROM FALSE POSITIVE RATE
spec = [1 - x for x in fpr]

#
# PLOT
#
ax = plt.axes()
# USE AN F-STRING TO INCLUDE THE AUC IN THE TITLE
ax.set_title(
    'Receiver Operating Characteristic\n' +
    f'(AUC = {auc:4.2f})'
)
# PLOT THE ROC CURVE
ax.plot(spec, tpr, 'k-')
# PLOT THE DIAGONAL LINE (BE CAREFUL TO NOT START AT THE ORIGIN)
ax.plot([1, 0], [0, 1], 'k-', alpha=0.3)
# REVERSE THE X-AXIS
ax.set_xlim([1, 0])
ax.set_ylim([0, 1])
ax.set_xlabel('Specificity')
ax.set_ylabel('Sensitivity')
# MAKE THE PLOT SQUARE
ax.set_aspect(abs(max(fpr) - min(fpr)) / abs(max(tpr) - min(tpr)))
plt.show()
plt.close()
```

[⇦ Back](../../../python.html)

</font>
