name: Update Website

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        # Install Python dependencies
        pip install -r requirements.txt
        # Install R
        sudo apt-get install r-base
        # Install R Markdown package
        R -e "install.packages('rmarkdown', lib='~/R/libs')"

    - name: Run Python Scripts
      run: |
        python get_flag_status.py
        python analyse_flag_status.py -l
        
    - name: Run R Markdown Script
      run: |
        Rscript -e "rmarkdown::render('isis_flag_history.Rmd')"
        
    - name: Setup Pages
      uses: actions/configure-pages@v4
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        # Upload entire repository
        path: '.'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
        
    - name: Commit and Push Changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update website" || true
